export const turkiyeIller = [
  { il: "Adana", ilceler: ["Seyhan", "Çukurova", "Yüreğir", "Sarıçam", "Ceyhan", "Kozan", "İmamoğlu", "Karataş", "Pozantı", "Saimbeyli", "Tufanbeyli", "Yumurtalık", "Aladağ", "Feke", "Karaisalı"] },
  { il: "Adıyaman", ilceler: ["Merkez", "Kahta", "Besni", "Gölbaşı", "Gerger", "Sincik", "Çelikhan", "Tut", "Samsat"] },
  { il: "Afyonkarahisar", ilceler: ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ", "Sinanpaşa", "Şuhut", "Çay", "İhsaniye", "İscehisar", "Sultandağı", "Çobanlar", "Dazkırı", "Evciler", "Hocalar", "Kızılören"] },
  { il: "Ağrı", ilceler: ["Merkez", "Patnos", "Doğubayazıt", "Diyadin", "Eleşkirt", "Tutak", "Taşlıçay", "Hamur"] },
  { il: "Amasya", ilceler: ["Merkez", "Merzifon", "Suluova", "Taşova", "Gümüşhacıköy", "Göynücek", "Hamamözü"] },
  { il: "Ankara", ilceler: ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Pursaklar", "Gölbaşı", "Polatlı", "Çubuk", "Kahramankazan", "Beypazarı", "Elmadağ", "Şereflikoçhisar", "Akyurt", "Nallıhan", "Haymana", "Kızılcahamam", "Bala", "Kalecik", "Ayaş", "Güdül", "Çamlıdere", "Evren"] },
  { il: "Antalya", ilceler: ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik", "Aksu", "Döşemealtı", "Kumluca", "Kaş", "Korkuteli", "Gazipaşa", "Finike", "Kemer", "Elmalı", "Demre", "Akseki", "Gündoğmuş", "İbradı"] },
  { il: "Artvin", ilceler: ["Merkez", "Hopa", "Borçka", "Arhavi", "Şavşat", "Ardanuç", "Yusufeli", "Murgul", "Kemalpaşa"] },
  { il: "Aydın", ilceler: ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "Çine", "İncirliova", "Germencik", "Bozdoğan", "Köşk", "Kuyucak", "Sultanhisar", "Karacasu", "Yenipazar", "Buharkent", "Karpuzlu", "Koçarlı"] },
  { il: "Balıkesir", ilceler: ["Karesi", "Altıeylül", "Bandırma", "Edremit", "Gönen", "Ayvalık", "Burhaniye", "Bigadiç", "Susurluk", "Dursunbey", "Sındırgı", "İvrindi", "Havran", "Erdek", "Manyas", "Savaştepe", "Balya", "Gömeç", "Marmara", "Kepsut"] },
  { il: "Bilecik", ilceler: ["Merkez", "Bozüyük", "Osmaneli", "Söğüt", "Gölpazarı", "Pazaryeri", "Yenipazar", "İnhisar"] },
  { il: "Bingöl", ilceler: ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı", "Kiğı", "Yedisu", "Yayladere"] },
  { il: "Bitlis", ilceler: ["Merkez", "Tatvan", "Güroymak", "Ahlat", "Hizan", "Mutki", "Adilcevaz"] },
  { il: "Bolu", ilceler: ["Merkez", "Gerede", "Mudurnu", "Göynük", "Mengen", "Yeniçağa", "Dörtdivan", "Seben", "Kıbrıscık"] },
  { il: "Burdur", ilceler: ["Merkez", "Bucak", "Gölhisar", "Yeşilova", "Çavdır", "Tefenni", "Ağlasun", "Karamanlı", "Altınyayla", "Çeltikçi", "Kemer"] },
  { il: "Bursa", ilceler: ["Osmangazi", "Yıldırım", "Nilüfer", "İnegöl", "Gemlik", "Mustafakemalpaşa", "Mudanya", "Gürsu", "Karacabey", "Orhangazi", "Kestel", "Yenişehir", "İznik", "Orhaneli", "Keles", "Büyükorhan", "Harmancık"] },
  { il: "Çanakkale", ilceler: ["Merkez", "Biga", "Çan", "Gelibolu", "Ayvacık", "Ezine", "Yenice", "Bayramiç", "Lapseki", "Eceabat", "Gökçeada", "Bozcaada"] },
  { il: "Çankırı", ilceler: ["Merkez", "Çerkeş", "Ilgaz", "Orta", "Şabanözü", "Kurşunlu", "Yapraklı", "Eldivan", "Kızılırmak", "Atkaracalar", "Korgun", "Bayramören"] },
  { il: "Çorum", ilceler: ["Merkez", "Sungurlu", "Osmancık", "İskilip", "Alaca", "Bayat", "Mecitözü", "Kargı", "Ortaköy", "Uğurludağ", "Dodurga", "Oğuzlar", "Laçin", "Boğazkale"] },
  { il: "Denizli", ilceler: ["Pamukkale", "Merkezefendi", "Çivril", "Acıpayam", "Tavas", "Honaz", "Sarayköy", "Buldan", "Kale", "Çal", "Serinhisar", "Bozkurt", "Güney", "Çardak", "Bekilli", "Beyağaç", "Babadağ", "Baklan"] },
  { il: "Diyarbakır", ilceler: ["Bağlar", "Kayapınar", "Yenişehir", "Ergani", "Bismil", "Sur", "Silvan", "Çınar", "Çermik", "Dicle", "Kulp", "Hani", "Lice", "Eğil", "Hazro", "Kocaköy", "Çüngüş"] },
  { il: "Edirne", ilceler: ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa", "Meriç", "Enez", "Süloğlu", "Lalapaşa"] },
  { il: "Elazığ", ilceler: ["Merkez", "Kovancılar", "Karakoçan", "Palu", "Arıcak", "Baskil", "Maden", "Sivrice", "Alacakaya", "Keban", "Ağın"] },
  { il: "Erzincan", ilceler: ["Merkez", "Tercan", "Üzümlü", "Çayırlı", "İliç", "Kemah", "Kemaliye", "Refahiye", "Otlukbeli"] },
  { il: "Erzurum", ilceler: ["Yakutiye", "Palandöken", "Aziziye", "Horasan", "Oltu", "Pasinler", "Karayazı", "Hınıs", "Tekman", "Karaçoban", "Aşkale", "Şenkaya", "Çat", "Köprüköy", "İspir", "Tortum", "Narman", "Uzundere", "Olur", "Pazaryolu"] },
  { il: "Eskişehir", ilceler: ["Odunpazarı", "Tepebaşı", "Sivrihisar", "Çifteler", "Seyitgazi", "Alpu", "Mihalıççık", "Mahmudiye", "Beylikova", "İnönü", "Günyüzü", "Sarıcakaya", "Mihalgazi", "Han"] },
  { il: "Gaziantep", ilceler: ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Araban", "Oğuzeli", "Yavuzeli", "Karkamış"] },
  { il: "Giresun", ilceler: ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu", "Şebinkarahisar", "Keşap", "Dereli", "Yağlıdere", "Piraziz", "Eynesil", "Alucra", "Çamoluk", "Güce", "Doğankent", "Çanakçı"] },
  { il: "Gümüşhane", ilceler: ["Merkez", "Kelkit", "Şiran", "Kürtün", "Torul", "Köse"] },
  { il: "Hakkari", ilceler: ["Merkez", "Yüksekova", "Şemdinli", "Çukurca", "Derecik"] },
  { il: "Hatay", ilceler: ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ", "Kırıkhan", "Reyhanlı", "Arsuz", "Altınözü", "Hassa", "Erzin", "Payas", "Belen", "Yayladağı", "Kumlu"] },
  { il: "Isparta", ilceler: ["Merkez", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Yalvaç", "Keçiborlu", "Senirkent", "Sütçüler", "Gönen", "Uluborlu", "Atabey", "Aksu", "Yenişarbademli"] },
  { il: "Mersin", ilceler: ["Tarsus", "Toroslar", "Yenişehir", "Akdeniz", "Mezitli", "Erdemli", "Silifke", "Anamur", "Mut", "Bozyazı", "Gülnar", "Aydıncık", "Çamlıyayla"] },
  { il: "İstanbul", ilceler: ["Esenyurt", "Küçükçekmece", "Bağcılar", "Pendik", "Ümraniye", "Bahçelievler", "Üsküdar", "Sultangazi", "Maltepe", "Gaziosmanpaşa", "Kartal", "Kadıköy", "Esenler", "Kağıthane", "Fatih", "Avcılar", "Başakşehir", "Ataşehir", "Sancaktepe", "Eyüpsultan", "Beylikdüzü", "Sarıyer", "Sultanbeyli", "Zeytinburnu", "Güngören", "Arnavutköy", "Şişli", "Bayrampaşa", "Tuzla", "Çekmeköy", "Büyükçekmece", "Beyoğlu", "Bakırköy", "Beşiktaş", "Silivri", "Çatalca", "Şile", "Adalar"] },
  { il: "İzmir", ilceler: ["Buca", "Karabağlar", "Bornova", "Konak", "Karşıyaka", "Bayraklı", "Çiğli", "Torbalı", "Menemen", "Gaziemir", "Ödemiş", "Kemalpaşa", "Bergama", "Tire", "Balçova", "Menderes", "Aliağa", "Narlıdere", "Urla", "Seferihisar", "Çeşme", "Kiraz", "Dikili", "Foça", "Bayındır", "Selçuk", "Güzelbahçe", "Kınık", "Beydağ", "Karaburun"] },
  { il: "Kars", ilceler: ["Merkez", "Kağızman", "Sarıkamış", "Selim", "Digor", "Arpaçay", "Akyaka", "Susuz"] },
  { il: "Kastamonu", ilceler: ["Merkez", "Tosya", "Taşköprü", "Cide", "İnebolu", "Araç", "Devrekani", "Bozkurt", "Küre", "Abana", "Çatalzeytin", "Daday", "Azdavay", "Şenpazar", "Pınarbaşı", "Seydiler", "Hanönü", "Kasaba", "İhsangazi", "Ağlı"] },
  { il: "Kayseri", ilceler: ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı", "Bünyan", "İncesu", "Pınarbaşı", "Tomarza", "Yeşilhisar", "Sarıoğlan", "Hacılar", "Sarız", "Akkışla", "Felahiye", "Özvatan"] },
  { il: "Kırklareli", ilceler: ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar", "Demirköy", "Pehlivanköy", "Kofçaz"] },
  { il: "Kırşehir", ilceler: ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar", "Boztepe", "Akçakent"] },
  { il: "Kocaeli", ilceler: ["Gebze", "İzmit", "Darıca", "Körfez", "Gölcük", "Derince", "Çayırova", "Kartepe", "Başiskele", "Karamürsel", "Dilovası", "Kandıra"] },
  { il: "Konya", ilceler: ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Çumra", "Seydişehir", "Cihanbeyli", "Kulu", "Ilgın", "Bozyazı", "Kadirli", "Sarayönü", "Kadınhanı"] },
  { il: "Kütahya", ilceler: ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet", "Altıntaş", "Domaniç", "Hisarcık", "Aslanapa", "Çavdarhisar", "Şaphane", "Pazarlar", "Dumlupınar"] },
  { il: "Malatya", ilceler: ["Yeşilyurt", "Battalgazi", "Doğanşehir", "Akçadağ", "Darende", "Hekimhan", "Pütürge", "Yazıhan", "Arapgir", "Kuluncak", "Arguvan", "Kale", "Doğanyol"] },
  { il: "Manisa", ilceler: ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Soma", "Salihli", "Saruhanlı", "Alaşehir", "Kula", "Demirci", "Gördes", "Sarıgöl", "Selendi", "Ahmetli", "Gölmarmara", "Köprübaşı"] },
  { il: "Kahramanmaraş", ilceler: ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin", "Türkoğlu", "Pazarcık", "Göksun", "Andırın", "Çağlayancerit", "Nurhak", "Ekinözü"] },
  { il: "Mardin", ilceler: ["Kızıltepe", "Artuklu", "Midyat", "Nusaybin", "Derik", "Mazıdağı", "Dargeçit", "Savur", "Yeşilli", "Ömerli"] },
  { il: "Muğla", ilceler: ["Bodrum", "Fethiye", "Milas", "Menteşe", "Marmaris", "Seydikemer", "Yatağan", "Ortaca", "Dalaman", "Köyceğiz", "Ula", "Datça", "Kavaklıdere"] },
  { il: "Muş", ilceler: ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy", "Korkut"] },
  { il: "Nevşehir", ilceler: ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Derinkuyu", "Acıgöl", "Kozaklı", "Hacıbektaş"] },
  { il: "Niğde", ilceler: ["Merkez", "Bor", "Çiftlik", "Ulukışla", "Altunhisar", "Çamardı"] },
  { il: "Ordu", ilceler: ["Altınordu", "Ünye", "Fatsa", "Gölköy", "Korgan", "Kumru", "Perşembe", "Akkuş", "Aybastı", "Ulubey", "Mesudiye", "İkizce", "Gürgentepe", "Çatalpınar", "Çaybaşı", "Kabataş", "Kabadüz", "Gülyalı", "Çamaş"] },
  { il: "Rize", ilceler: ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Fındıklı", "Güneysu", "Kalkandere", "İyidere", "Derepazarı", "Çamlıhemşin", "İkizdere", "Hemşin"] },
  { il: "Sakarya", ilceler: ["Adapazarı", "Serdivan", "Akyazı", "Erenler", "Hendek", "Karasu", "Geyve", "Arifiye", "Sapanca", "Pamukova", "Ferizli", "Kocaali", "Kocaali", "Kaynarca", "Söğütlü", "Karapürçek", "Taraklı"] },
  { il: "Samsun", ilceler: ["İlkadım", "Atakum", "Bafra", "Çarşamba", "Canik", "Vezirköprü", "Terme", "Tekkeköy", "Havza", "19 Mayıs", "Alaçam", "Salıpazarı", "Ayvacık", "Kavak", "Asarcık", "Ladik", "Yakakent"] },
  { il: "Siirt", ilceler: ["Merkez", "Kurtalan", "Baykan", "Pervari", "Eruh", "Şirvan", "Tillo"] },
  { il: "Sinop", ilceler: ["Merkez", "Boyabat", "Gerze", "Ayancık", "Durağan", "Türkeli", "Erfelek", "Saraydüzü", "Dikmen"] },
  { il: "Sivas", ilceler: ["Merkez", "Şarkışla", "Yıldızeli", "Suşehri", "Gemerek", "Zara", "Kangal", "Gürün", "Divriği", "Koyulhisar", "Altınyayla", "Haif", "İmranlı", "Akıncılar", "Ulaş", "Doğanşar", "Gölova"] },
  { il: "Tekirdağ", ilceler: ["Çorlu", "Süleymanpaşa", "Çerkezköy", "Kapaklı", "Ergene", "Malkara", "Saray", "Hayrabolu", "Şarköy", "Muratlı", "Marmaraereğlisi"] },
  { il: "Tokat", ilceler: ["Merkez", "Erbaa", "Turhal", "Niksar", "Zile", "Reşadiye", "Almus", "Pazar", "Yeşilyurt", "Artova", "Sulusaray", "Başçiftlik"] },
  { il: "Trabzon", ilceler: ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Sürmene", "Arsin", "Vakfıkebir", "Maçka", "Beşikdüzü", "Çarşıbaşı", "Tonya", "Düzköy", "Çaykara", "Şalpazarı", "Hayrat", "Köprübaşı", "Dernekpazarı"] },
  { il: "Tunceli", ilceler: ["Merkez", "Pertek", "Mazgirt", "Çemişgezek", "Hozat", "Ovacık", "Pülümür", "Nazımiye"] },
  { il: "Şanlıurfa", ilceler: ["Eyyübiye", "Haliliye", "Siverek", "Viranşehir", "Karaköprü", "Akçakale", "Suruç", "Birecik", "Ceylanpınar", "Harran", "Bozova", "Hilvan", "Halfeti"] },
  { il: "Uşak", ilceler: ["Merkez", "Banaz", "Eşme", "Sivaslı", "Ulubey", "Karahallı"] },
  { il: "Van", ilceler: ["İpekyolu", "Erciş", "Tuşba", "Edremit", "Özalp", "Çaldıran", "Başkale", "Muradiye", "Gürpınar", "Gevaş", "Saray", "Çatak", "Bahçesaray"] },
  { il: "Yozgat", ilceler: ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy", "Boğazlıyan", "Sarıkaya", "Çekerek", "Şefaatli", "Saraykent", "Çayıralan", "Kadışehri", "Aydıncık", "Yenifakılı", "Çandır"] },
  { il: "Zonguldak", ilceler: ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Kozlu", "Alaplı", "Kilimli", "Gökçebey"] },
  { il: "Aksaray", ilceler: ["Merkez", "Eskil", "Ortaköy", "Gülağaç", "Güzelyurt", "Ağaçören", "Sarıyahşi", "Sultanhanı"] },
  { il: "Bayburt", ilceler: ["Merkez", "Aydıntepe", "Demirözü"] },
  { il: "Karaman", ilceler: ["Merkez", "Ermenek", "Sarıveliler", "Ayrancı", "Kazımkarabekir", "Başyayla"] },
  { il: "Kırıkkale", ilceler: ["Merkez", "Yahşihan", "Keskin", "Delice", "Bahşili", "Sulakyurt", "Balışeyh", "Çelebi", "Karakeçili"] },
  { il: "Batman", ilceler: ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş", "Hasankeyf"] },
  { il: "Şırnak", ilceler: ["Cizre", "Silopi", "Merkez", "İdil", "Uludere", "Beytüşşebap", "Güçlükonak"] },
  { il: "Bartın", ilceler: ["Merkez", "Amasra", "Ulus", "Kurucaşile"] },
  { il: "Ardahan", ilceler: ["Merkez", "Göle", "Çıldır", "Hanak", "Posof", "Damal"] },
  { il: "Iğdır", ilceler: ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"] },
  { il: "Yalova", ilceler: ["Merkez", "Çiftlikköy", "Çınarcık", "Altınova", "Armutlu", "Termal"] },
  { il: "Karabük", ilceler: ["Merkez", "Safranbolu", "Eskipazar", "Yenice", "Eflani", "Ovacık"] },
  { il: "Kilis", ilceler: ["Merkez", "Musabeyli", "Elbeyli", "Polateli"] },
  { il: "Osmaniye", ilceler: ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Toprakkale", "Sumbas", "Hasanbeyli"] },
  { il: "Düzce", ilceler: ["Merkez", "Akçakoca", "Kaynaşlı", "Gölyaka", "Çilimli", "Gümüşova", "Cumayeri", "Yığılca"] }
];
